version: '3'
services:
  backend:
    image: auction-backend
    environment:
      - DB_NAME=${DB_NAME}
      - PG_HOST=${PG_HOST}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_PORT=${PG_PORT}
      - PG_USERNAME=${PG_USERNAME}
      - PORT=${PORT}
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 6969:6969
    volumes:
      - .:/app