name: Deploy to Production

on:
  push:
    branches: [ "main" ]

env:
  DB_NAME: ${{ secrets.DB_NAME }}
  PG_HOST: ${{ secrets.PG_HOST }}
  PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
  PG_PORT: ${{ secrets.PG_PORT }}
  PG_USERNAME: ${{ secrets.PG_USERNAME }}
  PORT: ${{ secrets.PORT }}

jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v3
    - name: Set Environment Variables
      run: echo $ENV_FILE > .env
    - name: Docker Compose
      run: docker-compose up -d --force-recreate --build 